name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
  pull_request:
    branches: 
      - master
      - develop
      - release/*
      - feature/*
      
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
          
    - name: Check out Code 
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml  
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build 
      run: dotnet build System.Diagnostics.Abstracted.sln --configuration Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore

    - name: Run Tests
      run: dotnet test System.Diagnostics.Abstracted.sln --configuration Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} --no-build --verbosity normal

    - name: Create packages
      run: dotnet pack --configuration Release --output ./packages /p:Version=${{ steps.gitversion.outputs.NuGetVersion }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NuGet packages
        path: packages/*.*
        
#     - name: Push generated package to GitHub registry
#       if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
#       run: dotnet nuget push ./package/*.nupkg  --source "https://nuget.pkg.github.com/threenine/index.json"  --api-key ${{ github.token }}

#    - name: Push generated package to nuget registry
#      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
#      run: dotnet nuget push ./package/*.nupkg  --source "https://api.nuget.org/v3/index.json"  -k ${{ secrets.NUGET_API_KEY }}
